# This is a basic workflow to help you get started with Actions

name: CI

# L'intégration continue se déclanche lors d'un pull_request
# et uniquement au push du fichier sample.tex
on:
  push:
    branches: [ master ]
    paths:
      - '*'
      - '!./sample.tex'

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # On installe xelatex
      - name: install xelatex
        run : sudo apt-get install texlive-xetex

      # On compile sample.tex
      - name: Compile sample.tex
        run: xelatex ./sample.tex

      # On enlève les les fichier .pdf de gitignore
      - name: remove file .pdf in .gitignore
        run: sed -i '/.*\.pdf/d' ./.gitignore # à rectifier le problème du pull à chaque re push local

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add sample.pdf
          git commit -m "Auto updating of sample.pdf"
      
      - name: push
        run: git push